apiVersion: v1
kind: Service
metadata:
  name: cohere-service
spec:
  type: NodePort
  selector:
    app: cohere-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30037
